-- values are given in the range of (0 - 255)!
---@alias ColorRgb255 {r: number, g: number, b: number, a: number}
---@alias AdventureType {title: string, level: number, duration: number, command: string}